In [1]:
import pandas as pd

In [2]:
#task----> to import data to python
df = pd.read_csv(r'C:\Users\Satyam\Downloads\Indian Startup.csv')

In [4]:
df.head()

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021

In [5]:
df.isnull().sum()

Company/Brand      0
Founded            1
Headquarters       1
Sector             0
What it does       0
Founder/s          4
Investor/s        63
Amount             7
Stage            428
Date               0
dtype: int64

In [6]:
df.shape

(1209, 10)

In [7]:
# drop
df.head()

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021

In [10]:
df1 = df.drop(['Company/Brand'],axis=1)

In [9]:
df.head()

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021

In [11]:
df1

,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021
...,...,...,...,...,...,...,...,...,...
1204,2019.0,Mumbai,EdTech,HobSpace is a platform for extra-curricular ac...,"Priya Goel Sheth, Harsh Jain","Siddharth Bhaskar Shah, Upsparks","$100,000",Pre-series A1,Jan-2021
1205,2020.0,New Delhi,EdTech,EMPOWER LEARNERS TO BE FUTURE READY USING AI,"Kartik Sharma, Ashish Aggarwal",S Chand,"$500,000",NaN,Jan-2021
1206,1978.0,Bangalore,BioTechnology,Biocon is a fully integrated pure play biosimi...,Kiran Mazumdar-Shaw,"Goldman Sachs, Tata Capital","$70,000,000",NaN,Jan-2021
1207,2020.0,Mumbai,E-commerce,A better model for instant grocery delivery in...,"Kaivalya Vohra, Aadit Palicha",Global Founders Capital,"$720,000",Pre-seed,Jan-2021
1208,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [13]:
# dropna
x = df.dropna()

In [14]:
x

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021
6,Pocket FM,2018.0,Bangalore,OTT,Pocket FM lets users discover and enjoy the gr...,"Rohan, Nishanth Srinivas, Prateek Dixit","Lightspeed, Times Group, Tanglin Venture Partners","$22,000,000",Series B,Dec-2021
8,PlanetSpark,2017.0,Gurugram,Education Management,PlanetSpark is building the World Leader in Co...,"Maneesh Dhooper, Kunal Malik","Binny Bansal, Deep Kalra, Dr Ashish Gupta, Gok...","$13,000,000",Series B,Dec-2021
...,...,...,...,...,...,...,...,...,...,...
1201,Oyo,2012.0,Gurgaon,Hospitality,OYO operates a branded network of hotels desig...,Ritesh Agarwal,Hindustan Media Venture,"$7,000,000",Series F1,Jan-2021
1202,Agri10x,2018.0,Pune,AgriTech,Agri10x integrates the entire Agri value-chain...,"Abhijith Naraparaju, Pankajj P. Ghode, Sundeep...",Omnivore,$Undisclosed,Seed,Jan-2021
1204,HobSpace,2019.0,Mumbai,EdTech,HobSpace is a platform for extra-curricular ac...,"Priya Goel Sheth, Harsh Jain","Siddharth Bhaskar Shah, Upsparks","$100,000",Pre-series A1,Jan-2021
1207,KiranaKart,2020.0,Mumbai,E-commerce,A better model for instant grocery delivery in...,"Kaivalya Vohra, Aadit Palicha",Global Founders Capital,"$720,000",Pre-seed,Jan-2021
1208,Meddo,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [15]:
x.isnull().sum()

Company/Brand    0
Founded          0
Headquarters     0
Sector           0
What it does     0
Founder/s        0
Investor/s       0
Amount           0
Stage            0
Date             0
dtype: int64

In [16]:
x.shape

(736, 10)

In [17]:
df.shape

(1209, 10)

In [19]:
# serching
#loc & iloc
# loc----> location based serching
# iloc----> index based location searching
df.loc()

In [25]:
df.loc[df['Sector']=='OTT']

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
6,Pocket FM,2018.0,Bangalore,OTT,Pocket FM lets users discover and enjoy the gr...,"Rohan, Nishanth Srinivas, Prateek Dixit","Lightspeed, Times Group, Tanglin Venture Partners","$22,000,000",Series B,Dec-2021

In [29]:
df.loc[df['Company/Brand']=='Meddo']

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
822,Meddo,2018.0,Gurugram,Healthcare,Meddo (Arctern Healthcare) are re-defining how...,"Saurabh Kochhar, Dr Naveen Nishchal","SRI Capital, Picus Capital, Alkemi Capital","$6,000,000",NaN,Jun-2021
1208,Meddo,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [30]:
# use loc to search the data from df
# 1. find the name & founded year of edtech comapnies.
df

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021
...,...,...,...,...,...,...,...,...,...,...
1204,HobSpace,2019.0,Mumbai,EdTech,HobSpace is a platform for extra-curricular ac...,"Priya Goel Sheth, Harsh Jain","Siddharth Bhaskar Shah, Upsparks","$100,000",Pre-series A1,Jan-2021
1205,DcodeAI,2020.0,New Delhi,EdTech,EMPOWER LEARNERS TO BE FUTURE READY USING AI,"Kartik Sharma, Ashish Aggarwal",S Chand,"$500,000",NaN,Jan-2021
1206,Biocon Biologics,1978.0,Bangalore,BioTechnology,Biocon is a fully integrated pure play biosimi...,Kiran Mazumdar-Shaw,"Goldman Sachs, Tata Capital","$70,000,000",NaN,Jan-2021
1207,KiranaKart,2020.0,Mumbai,E-commerce,A better model for instant grocery delivery in...,"Kaivalya Vohra, Aadit Palicha",Global Founders Capital,"$720,000",Pre-seed,Jan-2021
1208,Meddo,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [48]:
# 1. find the name & founded year of edtech + e-comm comapnies.
df.loc[df['Sector']=='EdTech' , df['Sector']=='E-commerce'][['Company/Brand','Founded','Headquarters']]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [36]:
df.loc[df['Sector']=='EdTech',['Company/Brand','Founded']]

            Company/Brand  Founded
186                BYJU'S   2011.0
192   Sunstone Eduversity   2011.0
254                Questt   2020.0
372             EventBeep   2019.0
382              Tinkerly   2015.0
...                   ...      ...
1181             Pariksha   2015.0
1189          Practically   2018.0
1195                  Kyt   2020.0
1204             HobSpace   2019.0
1205              DcodeAI   2020.0

[102 rows x 2 columns]

In [38]:
df2=df.loc[df["Sector"]=="EdTech"][["Company/Brand","Founded"]]
df2

            Company/Brand  Founded
186                BYJU'S   2011.0
192   Sunstone Eduversity   2011.0
254                Questt   2020.0
372             EventBeep   2019.0
382              Tinkerly   2015.0
...                   ...      ...
1181             Pariksha   2015.0
1189          Practically   2018.0
1195                  Kyt   2020.0
1204             HobSpace   2019.0
1205              DcodeAI   2020.0

[102 rows x 2 columns]