In [1]:
import pandas as pd

In [9]:
#wap to make dict!!
x = {
    'name':['ABC','dsfg','rrr','bahuballi'],
    'age':[34,45,56,67],
    'marks':[200,34,52,12]
}

In [10]:
x

{'name': ['ABC', 'dsfg', 'rrr', 'bahuballi'],
 'age': [34, 45, 56, 67],
 'marks': [200, 34, 52, 12]}

In [12]:
df = pd.DataFrame(x,index=[0,1,2,3])

In [13]:
df

        name  age  marks
0        ABC   34    200
1       dsfg   45     34
2        rrr   56     52
3  bahuballi   67     12

In [15]:
# Slicing 
df['name'][0]

'ABC'

In [19]:
df[['name','marks']]

        name  marks
0        ABC    200
1       dsfg     34
2        rrr     52
3  bahuballi     12

In [20]:
df

        name  age  marks
0        ABC   34    200
1       dsfg   45     34
2        rrr   56     52
3  bahuballi   67     12

In [22]:
#store the data in the form of a file

file = df.to_csv('mynewfile.csv')

In [23]:
file

In [25]:
#task----> to import data to python
df1 = pd.read_csv(r'C:\Users\Satyam\Downloads\Indian Startup.csv')

In [26]:
df1

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Studentâ€™s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021
...,...,...,...,...,...,...,...,...,...,...
1204,HobSpace,2019.0,Mumbai,EdTech,HobSpace is a platform for extra-curricular ac...,"Priya Goel Sheth, Harsh Jain","Siddharth Bhaskar Shah, Upsparks","$100,000",Pre-series A1,Jan-2021
1205,DcodeAI,2020.0,New Delhi,EdTech,EMPOWER LEARNERS TO BE FUTURE READY USING AI,"Kartik Sharma, Ashish Aggarwal",S Chand,"$500,000",NaN,Jan-2021
1206,Biocon Biologics,1978.0,Bangalore,BioTechnology,Biocon is a fully integrated pure play biosimi...,Kiran Mazumdar-Shaw,"Goldman Sachs, Tata Capital","$70,000,000",NaN,Jan-2021
1207,KiranaKart,2020.0,Mumbai,E-commerce,A better model for instant grocery delivery in...,"Kaivalya Vohra, Aadit Palicha",Global Founders Capital,"$720,000",Pre-seed,Jan-2021
1208,Meddo,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [28]:
#task to observe data
# head
# tail
# sample
df1.head()

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Studentâ€™s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021

In [29]:
df1.head(10)

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
0,CollegeDekho,2015.0,Gurgaon,E-learning,"Collegedekho.com is Studentâ€™s Partner, Friend ...",Ruchir Arora,"Disrupt ADQ, QIC","$35,000,000",Series B,Dec-2021
1,BOX8,2012.0,Mumbai,Food & Beverages,India's Largest Desi Meals Brand,"Anshul Gupta, Amit Raj",Tiger Global,"$40,000,000",NaN,Dec-2021
2,Simpl,2015.0,Bangalore,Consumer Services,Simpl empowers merchants to build trusted rela...,"Nitya, Chaitra Chidanand","Valar Ventures, IA Ventures","$40,000,000",Series B,Dec-2021
3,8i Ventures,2018.0,Mumbai,Venture Capital & Private Equity,8i is a Mumbai & Bangalore based early stage f...,Vikram Chachra,NaN,"$50,000,000",NaN,Dec-2021
4,PayGlocal,2021.0,Bangalore,Financial Services,PayGlocal is a FinTech solving for global paym...,"Prachi Dharani, Rohit Sukhija, Yogesh Lokhande",Sequoia Capital India,"$4,900,000",Series A,Dec-2021
5,Curefit,2016.0,Bangalore,"Health, Wellness & Fitness",Tata Digital-backed Curefit,"Mukesh Bansal, Ankit",Zomato,"$145,000,000",NaN,Dec-2021
6,Pocket FM,2018.0,Bangalore,OTT,Pocket FM lets users discover and enjoy the gr...,"Rohan, Nishanth Srinivas, Prateek Dixit","Lightspeed, Times Group, Tanglin Venture Partners","$22,000,000",Series B,Dec-2021
7,CHARGE+ZONE,2018.0,Vadodara,Automotive,CHARGE+ZONE is a tech-driven EV Charging infra...,Kartikey Hariyani,Venture Catalysts,"$10,000,000",NaN,Dec-2021
8,PlanetSpark,2017.0,Gurugram,Education Management,PlanetSpark is building the World Leader in Co...,"Maneesh Dhooper, Kunal Malik","Binny Bansal, Deep Kalra, Dr Ashish Gupta, Gok...","$13,000,000",Series B,Dec-2021
9,LenDenClub,2015.0,Mumbai,Financial Services,P2P lending platform delivering high returns o...,"Bhavin Patel, Dipesh Karki","Tuscan Ventures, Ohm Stock Brokers, Artha Vent...","$10,000,000",Series A,Dec-2021

In [32]:
# tail
df1.tail(12)

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
1197,BharatPe,2018.0,New Delhi,FinTech,BharatPe develops a QR code-based payment app ...,"Ashneer Grover, Shashvat Nakrani","Steadview Capital, Insight Partners","$8,200,000",Debt,Jan-2021
1198,CropIn,2010.0,Bangalore,AgriTech,CropIn is a leading AI and Data-led agri-tech ...,Krishna Kumar,"Invested Development, Pratithi Investment Trust","$20,000,000",Series C,Jan-2021
1199,Udaan,2016.0,Bangalore,E-commerce,Udaan is a B2B trade platform that brings manu...,"Amod Malviya, Sujeet Kumar, Vaibhav Gupta","Octahedron Capital, Moonstone Capital","$280,000,000",NaN,Jan-2021
1200,Vanity Wagon,2018.0,Haryana,Cosmetics,Vanity Wagon is Indiaâ€™s #1 Natural Organic Bea...,Prateek Ruhail,"Dhianu Das, Agility Venture Partners","$200,000",Seed,Jan-2021
1201,Oyo,2012.0,Gurgaon,Hospitality,OYO operates a branded network of hotels desig...,Ritesh Agarwal,Hindustan Media Venture,"$7,000,000",Series F1,Jan-2021
1202,Agri10x,2018.0,Pune,AgriTech,Agri10x integrates the entire Agri value-chain...,"Abhijith Naraparaju, Pankajj P. Ghode, Sundeep...",Omnivore,$Undisclosed,Seed,Jan-2021
1203,BlackSoil,2016.0,Mumbai,FinTech,Blacksoil Advisory is an independent boutique ...,Ankur Bansal,Awign Enterprises,"$4,000,000",NaN,Jan-2021
1204,HobSpace,2019.0,Mumbai,EdTech,HobSpace is a platform for extra-curricular ac...,"Priya Goel Sheth, Harsh Jain","Siddharth Bhaskar Shah, Upsparks","$100,000",Pre-series A1,Jan-2021
1205,DcodeAI,2020.0,New Delhi,EdTech,EMPOWER LEARNERS TO BE FUTURE READY USING AI,"Kartik Sharma, Ashish Aggarwal",S Chand,"$500,000",NaN,Jan-2021
1206,Biocon Biologics,1978.0,Bangalore,BioTechnology,Biocon is a fully integrated pure play biosimi...,Kiran Mazumdar-Shaw,"Goldman Sachs, Tata Capital","$70,000,000",NaN,Jan-2021
1207,KiranaKart,2020.0,Mumbai,E-commerce,A better model for instant grocery delivery in...,"Kaivalya Vohra, Aadit Palicha",Global Founders Capital,"$720,000",Pre-seed,Jan-2021
1208,Meddo,2018.0,Gurgaon,Healthcare,Meddo is an end-to-end medical services provider,Saurabh Kochhar,"growX ventures, Venture Gurukool","$3,000,000",Pre-series A,Jan-2021

In [38]:
#sample
df1.sample(3)

,Company/Brand,Founded,Headquarters,Sector,What it does,Founder/s,Investor/s,Amount,Stage,Date
1022,Juicy Chemistry,2014.0,Coimbatore,Healthcare,Juicy Chemistry operates as an eponymous consu...,"Megha, Pritesh Asher.",Akya Ventures,"$6,300,000",Series A,Mar-2021
1075,Aisle,2014.0,Bangalore,Dating,Aisle connects the new generation of single in...,Able Joseph,"Anas Rahman Junaid, Vinod Jose",$Undisclosed,Pre-series A,Feb-2021
1019,Chirrup,2020.0,Bangalore,Gaming,Video integrated social-gaming platform,"Vipul Garg, Sourav Lashkari, Mehul Mittal","Titan Capital, iSeed, First Cheque, 3.0 Fund.","$300,000",Pre-seed,Mar-2021